# Generated by Django 5.1 on 2024-10-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('spam_protection', models.CharField(max_length=50)),
            ],
        ),
    ]
