# Generated by Django 5.1 on 2024-10-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='spam_protection',
        ),
    ]
