# Generated by Django 5.1 on 2024-10-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactform_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Contact Form'},
        ),
        migrations.AlterField(
            model_name='bannerarea',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='bannerarea',
            index=models.Index(fields=['title'], name='contact_ban_title_a0bb02_idx'),
        ),
        migrations.AddIndex(
            model_name='contactform',
            index=models.Index(fields=['name'], name='contact_con_name_aa7e7e_idx'),
        ),
    ]
