# Generated by Django 5.1 on 2024-10-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('shop', '0002_alter_category_options_alter_checkout_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blog_banner',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['title', 'category', 'status'], name='blog_blog_title_0c7af9_idx'),
        ),
        migrations.AddIndex(
            model_name='blog_banner',
            index=models.Index(fields=['title'], name='blog_blog_b_title_b6ab40_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['name', 'post'], name='blog_commen_name_bbd510_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='blog_tag_name_43b6ed_idx'),
        ),
    ]
