# Generated by Django 5.1 on 2024-08-16 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=100, verbose_name='Discription')),
                ('icon', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'About Store',
            },
        ),
        migrations.CreateModel(
            name='CustomerCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Customer Care',
            },
        ),
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Customer Service',
            },
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delas', models.CharField(choices=[('HOT SALE', 'HOT SALE'), ('NEW ARRIVALS', 'NEW ARRIVALS'), ('ON SALE', 'ON SALE')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturesArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('title', models.CharField(default='Feature Title', max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Feature Area',
            },
        ),
        migrations.CreateModel(
            name='Footerlinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Footer Links',
            },
        ),
        migrations.CreateModel(
            name='Moveing_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=100)),
                ('text2', models.CharField(blank=True, max_length=100)),
                ('text3', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Moveing Text',
            },
        ),
        migrations.CreateModel(
            name='Myaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'My Account',
            },
        ),
        migrations.CreateModel(
            name='Navbar_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/nav_logo/')),
            ],
            options={
                'verbose_name': 'Navbar',
            },
        ),
        migrations.CreateModel(
            name='payment_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/payment_img/')),
            ],
            options={
                'verbose_name': 'Payment Image',
            },
        ),
        migrations.CreateModel(
            name='Quicklinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Quick Link',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Social Media Link',
            },
        ),
        migrations.CreateModel(
            name='Banner_Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=False, upload_to='media/banner_top_imgs/')),
                ('discount', models.IntegerField()),
                ('quote', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('deals', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.deals', verbose_name='Discount Deals')),
            ],
            options={
                'verbose_name': 'Top Banner',
            },
        ),
        migrations.CreateModel(
            name='Banner_Middle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/bamiddle_imgs/')),
                ('quote', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('link', models.CharField(max_length=100)),
                ('deals', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.deals', verbose_name='Discount Deals')),
            ],
            options={
                'verbose_name': 'Banner Middle',
            },
        ),
        migrations.CreateModel(
            name='Banner_Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default=False, upload_to='media/bannutton_imgs/')),
                ('discount', models.IntegerField()),
                ('link', models.CharField(max_length=100)),
                ('deals', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.deals', verbose_name='Discount Deals')),
            ],
            options={
                'verbose_name': 'Banner Button',
            },
        ),
        migrations.CreateModel(
            name='Banner_Bottom_middle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default=False, upload_to='media/bannutton_imgs/')),
                ('link', models.CharField(max_length=100)),
                ('deals', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.deals', verbose_name='Discount Deals')),
            ],
            options={
                'verbose_name': 'Banner Bottom Middle',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(blank=True)),
                ('sales', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default=True, upload_to='media/slimgs/', verbose_name='Slider Image')),
                ('link', models.CharField(max_length=100)),
                ('barnd_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Brand Name')),
                ('discount_deals', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.deals', verbose_name='Discount Deals')),
            ],
        ),
        migrations.CreateModel(
            name='Special_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Special Offer',
            },
        ),
        migrations.CreateModel(
            name='Top_deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Top Deal',
            },
        ),
        migrations.CreateModel(
            name='Top_sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Top Sell',
            },
        ),
    ]
