# Generated by Django 5.1 on 2024-08-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_download_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_app',
            name='link',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
