# Generated by Django 5.1 on 2024-08-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_download_app_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Download_App',
        ),
    ]
