# Generated by Django 5.1 on 2024-10-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_download_app'),
        ('shop', '0002_alter_category_options_alter_checkout_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deals',
            options={'verbose_name': 'Deal'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider'},
        ),
        migrations.AlterField(
            model_name='aboutstore',
            name='descr',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Discription'),
        ),
        migrations.AlterField(
            model_name='banner_bottom_middle',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='banner_button',
            name='image',
            field=models.ImageField(db_index=True, default=False, upload_to='media/bannutton_imgs/'),
        ),
        migrations.AlterField(
            model_name='banner_middle',
            name='quote',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customercare',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='featuresarea',
            name='title',
            field=models.CharField(db_index=True, default='Feature Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='footerlinks',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='moveing_text',
            name='text1',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='myaccount',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='navbar_text',
            name='logo',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='media/nav_logo/'),
        ),
        migrations.AlterField(
            model_name='navbar_text',
            name='text',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quicklinks',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='discount',
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, db_index=True, default=True, upload_to='media/slimgs/', verbose_name='Slider Image'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='url',
            field=models.URLField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='aboutstore',
            index=models.Index(fields=['descr'], name='home_abouts_descr_7d5832_idx'),
        ),
        migrations.AddIndex(
            model_name='banner_bottom_middle',
            index=models.Index(fields=['deals', 'title'], name='home_banner_deals_i_b34637_idx'),
        ),
        migrations.AddIndex(
            model_name='banner_button',
            index=models.Index(fields=['title', 'deals'], name='home_banner_title_8663ea_idx'),
        ),
        migrations.AddIndex(
            model_name='banner_middle',
            index=models.Index(fields=['deals', 'quote'], name='home_banner_deals_i_0b182d_idx'),
        ),
        migrations.AddIndex(
            model_name='banner_top',
            index=models.Index(fields=['deals'], name='home_banner_deals_i_3f2db6_idx'),
        ),
        migrations.AddIndex(
            model_name='customercare',
            index=models.Index(fields=['name'], name='home_custom_name_e58926_idx'),
        ),
        migrations.AddIndex(
            model_name='customerservice',
            index=models.Index(fields=['name'], name='home_custom_name_4cf664_idx'),
        ),
        migrations.AddIndex(
            model_name='deals',
            index=models.Index(fields=['delas'], name='home_deals_delas_c6a0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='featuresarea',
            index=models.Index(fields=['title'], name='home_featur_title_99ea43_idx'),
        ),
        migrations.AddIndex(
            model_name='footerlinks',
            index=models.Index(fields=['name'], name='home_footer_name_b1ff3b_idx'),
        ),
        migrations.AddIndex(
            model_name='moveing_text',
            index=models.Index(fields=['text1'], name='home_movein_text1_f9aa8e_idx'),
        ),
        migrations.AddIndex(
            model_name='myaccount',
            index=models.Index(fields=['name'], name='home_myacco_name_8acb75_idx'),
        ),
        migrations.AddIndex(
            model_name='navbar_text',
            index=models.Index(fields=['text'], name='home_navbar_text_4f8cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='quicklinks',
            index=models.Index(fields=['name'], name='home_quickl_name_1ede17_idx'),
        ),
        migrations.AddIndex(
            model_name='slider',
            index=models.Index(fields=['barnd_name', 'image', 'discount'], name='home_slider_barnd_n_e75d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmedialink',
            index=models.Index(fields=['name'], name='home_social_name_5c8809_idx'),
        ),
        migrations.AddIndex(
            model_name='special_offer',
            index=models.Index(fields=['name'], name='home_specia_name_id_4d57c3_idx'),
        ),
        migrations.AddIndex(
            model_name='top_deals',
            index=models.Index(fields=['name'], name='home_top_de_name_id_b6de6d_idx'),
        ),
        migrations.AddIndex(
            model_name='top_sell',
            index=models.Index(fields=['name'], name='home_top_se_name_id_bda1b3_idx'),
        ),
    ]
