# Generated by Django 5.1 on 2024-10-13 06:41

import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name': 'Checkout'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='cart_banner',
            name='title',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='checkout_banner',
            name='title',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_information',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shopbanner',
            name='text',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Size Name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Tag Name'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='shop_brand_name_c466ec_idx'),
        ),
        migrations.AddIndex(
            model_name='cart_banner',
            index=models.Index(fields=['title'], name='shop_cart_b_title_a0f2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product', 'user'], name='shop_cartit_product_83f9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='shop_catego_name_289c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['user', 'first_name', 'email', 'phone'], name='shop_checko_user_id_f6f294_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout_banner',
            index=models.Index(fields=['title'], name='shop_checko_title_4dc7a7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product', 'payment_method', 'status'], name='shop_order_product_6cdb5a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'description', 'additional_information', 'price', 'discount', 'availability', 'sku', 'size', 'image', 'features', 'categories', 'tags', 'stock', 'brand'], name='shop_produc_name_00e740_idx'),
        ),
        migrations.AddIndex(
            model_name='reviews',
            index=models.Index(fields=['product', 'name'], name='shop_review_product_39d452_idx'),
        ),
        migrations.AddIndex(
            model_name='shopbanner',
            index=models.Index(fields=['text'], name='shop_shopba_text_6b0c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='size',
            index=models.Index(fields=['name'], name='shop_size_name_473662_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='shop_tag_name_971c74_idx'),
        ),
    ]
