# Generated by Django 5.1 on 2024-08-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('Sub_desc', models.TextField(verbose_name='Short Description')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/about_section/')),
            ],
            options={
                'verbose_name': 'About Section',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Banner Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/about_banner/')),
                ('button_link', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('descr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Short Description')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/about_location/')),
                ('map_link', models.URLField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Location',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_area_title', models.CharField(blank=True, default='services_area_title', max_length=200, null=True)),
                ('services_area_description', models.TextField(default='services_area_description')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(max_length=50)),
                ('step_number', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Service',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('descr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Short Description')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/about_team/')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('dribbble', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/about_technology/', verbose_name='Image 1')),
                ('images', models.ImageField(blank=True, null=True, upload_to='media/about_technology/', verbose_name='Image 2')),
                ('active_clients', models.PositiveIntegerField(verbose_name='Active Clients In Numnber')),
                ('projects_done', models.PositiveIntegerField(verbose_name='Projects Done In Numnber')),
                ('team_advisors', models.PositiveIntegerField(verbose_name='Team Advisors In Numnber')),
                ('users_online', models.PositiveIntegerField(verbose_name='Users Online In Numnber')),
            ],
            options={
                'verbose_name': 'Technology',
                'ordering': ['title'],
            },
        ),
    ]
