# Generated by Django 5.1 on 2024-08-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukamarket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download_App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(default=False, max_length=100)),
                ('image', models.ImageField(upload_to='media/download_app/')),
            ],
        ),
    ]
